#literal-pod.yaml
apiVersion: v1
kind: Pod
metadata: 
  name: test-pod
spec:
  containers:
  - name: test-container
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "env" ]
    env: 
      - name: SPECIAL-LEVEL-KEY
        valueFrom: 
          configMapKeyRef: 
            name: special-config
            key: special.how
  restartPolicy: Never
