#mysecret-pod.yaml
apiVersion: v1
kind: Pod
metadata: 
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis:2.8.23
    volumeMounts:
    - mountPath: "/etc/foo"
      name: foo
      readOnly: true
  volumes:
  - name: foo
    secret:
     secretName: mysecret
