#mysecret-env-pod.yaml
apiVersion: v1
kind: Pod
metadata: 
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis:2.8.23
    env:
    - name: SECRET_USERNAME
      valueFrom: 
       secretKeyRef:
         name: mysecret
         key: username
    - name: SECRET_PASSWORD
      valueFrom: 
       secretKeyRef:
         name: mysecret
         key: password
  restartPolicy: Never
